// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppaFqvvvtAnzhoKpcfPUJ7KIVBYZTXIA',
    appId: '1:905299062212:web:cfe4f045504f048b76c891',
    messagingSenderId: '905299062212',
    projectId: 'ecommerce-93760',
    authDomain: 'ecommerce-93760.firebaseapp.com',
    storageBucket: 'ecommerce-93760.appspot.com',
    measurementId: 'G-C4ZTHZMF07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZPUzrUlPWMqKztqxdXrlqmbhmp48sZc',
    appId: '1:905299062212:android:5027c04733db322676c891',
    messagingSenderId: '905299062212',
    projectId: 'ecommerce-93760',
    storageBucket: 'ecommerce-93760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpV1I6SXm7fS50degX0zAHp2Xuv2re5U',
    appId: '1:905299062212:ios:f83635025b88454d76c891',
    messagingSenderId: '905299062212',
    projectId: 'ecommerce-93760',
    storageBucket: 'ecommerce-93760.appspot.com',
    iosBundleId: 'com.example.ecommerceMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpV1I6SXm7fS50degX0zAHp2Xuv2re5U',
    appId: '1:905299062212:ios:f83635025b88454d76c891',
    messagingSenderId: '905299062212',
    projectId: 'ecommerce-93760',
    storageBucket: 'ecommerce-93760.appspot.com',
    iosBundleId: 'com.example.ecommerceMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBppaFqvvvtAnzhoKpcfPUJ7KIVBYZTXIA',
    appId: '1:905299062212:web:87daf93a6e05a58876c891',
    messagingSenderId: '905299062212',
    projectId: 'ecommerce-93760',
    authDomain: 'ecommerce-93760.firebaseapp.com',
    storageBucket: 'ecommerce-93760.appspot.com',
    measurementId: 'G-MZW9RWBHT4',
  );
}
